# Oefeningen arrays en lists
## Oef1
Hoe kun je best(=op de meest efficiënte manier) bij elk element van de onderstaande array 1 optellen?

Output:

[ 2  3  4  5  6  7  8  9 10 11]

1) arr + 1
1) for item in arr: item = item + 1
1) for index in range(len(arr)): arr[index] += 1
1) arr = arr + 1

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#wat moet je hier invullen ? (meest efficiënte manier)
arr = arr + 1
print(arr)

[ 2  3  4  5  6  7  8  9 10 11]


## Oef2
Wat moet je in de onderstaande code invullen om de volgende output te krijgen:

[11 11 11 11 11 11 11 11 11 11]´

1) arr = arr + arr[::-1]
1) arr = arr + np.arange(10, 1, -1)
1) arr += arr[10:0:-1]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#wat moet je hier invullen?
print(arr)

## Oef3
Is er een verschil in resultaat tussen
`arr += 1`
en
`arr += np.ones_like(arr)`
1) ja
1) nee

## Oef4
Hoe kan ik het derde element van de eerste rij afdrukken in de volgende code? (meerdere antwoorden mogelijk)

1) print(arr[0, -1])
1) print(arr[0],[-1])
1) print(arr[0][-1])
1) print(arr[0, 3])
1) print(arr[0],[3])
1) print(arr[0][3])

In [ ]:
import numpy as np
lijst = [[1, 2, 3],[4, 5, 6]]
arr = np.array(lijst)
#welk print-statement moet ik hier invullen?

##  de onderstaande code. Hoe kan ik de laatste kolom van de array afdrukken?
De output zou dus het volgende moeten zijn:

[3 6 9]

1) print(arr[-1])
1) print(arr[][-1]
1) print(arr[:, -1]
1) print(arr[3])
1) print(arr[][3]
1) print(arr[:, 3]

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#welk print-statement moet je hier invullen om de laatste kolom te tonen?

## Oef6
Wat is de waarde van het tweede element van de array in de onderstaande code?

1) Er is geen waarde want je krijgt een fout
1) 128
1) -128

In [ ]:
import numpy as np
arr = np.arange(127, 138, dtype=np.int8)
#hoe zou je hier het tweede element van de array afdrukken?

## Oef7
Wat is de waarde van het eerste element van de som van de array met zichzelf?

1) Er is geen waarde want je krijgt een fout
1) 240
1) -16

In [ ]:
import numpy as np
arr = np.arange(120, 128, dtype=np.int8)
#Hoe druk je het eerste element van de som van de array met zichzelf af

## Oef8
Wat is het eerste element van arr / arr_2 in de volgende code?


1) Er is geen waarde want je krijgt een fout
1) inf
1) 1/256

In [ ]:
import numpy as np
arr = np.arange(1, 11, dtype=np.int8)
arr_2 = np.full_like(arr, 256)
#Hoe druk je hier het eerste element van arr / arr_2 af

## Oef9
Kijk eens bij de documentatie van np.full_like() om te zien wat je kunt doen om in de code van de vorige oefening toch 1/256 als resultaat te krijgen. Vul je antwoord hieronder in.



In [ ]:
import numpy as np
arr = np.arange(1, 11, dtype=np.int8)
#Wat moet je in het volgende statement veranderen om de code toch correct te laten werken?
arr_2 = np.full_like(arr, 256)
print((arr / arr_2)[0]) #Moet 0.00390625 zijn

## Oef10
In de volgende code wordt de som van de 3 getallen afgedrukt. Hoe zou je op de laatste regel ook de som van de 3 getallen kunnen afdrukken?
(Je mag eventueel ChatGPT gebruiken voor dit antwoord. Maar vermeld het dan wel bij je oplossing.)















In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(np.sum(arr))
arr = np.append(arr, 'test')
#welk print-statement moet je hier invullen om de som van de drie getallen af te drukken?

## Oplossingen oefeningen
### Oef1
De beste manier om 1 op te tellen bij elk element is arr = arr + 1(antwoord 4). Het antwoord 'arr + 1' verandert de array niet. Let op: arr += 1 zou de array wel veranderen. De andere oplossingen gebruiken een Python for-lus en zijn zeker niet de beste manier om het te doen.
## Oef2
Je krijgt het juiste resultaat met arr = arr + arr[::-1] (antwoord 1). De twee andere arrays zijn telkens maar 9 elementen lang.
## Oef3
Er is geen verschil in resultaat tussen beide statement. De functie np.ones_like in NumPy maakt een array met allemaal 1-en met dezelfde dimensies als de array *arr*.
## Oef4
Er zijn twee correcte antwoorden: arr[0, -1] en arr[0][-1]. De eerste heeft de voorkeur omdat we hier ineens de waarde opvragen. Bij de tweede gebeurt de opvraging in twee stappen: eerst vragen we de eerste rij op (arr[0]) en vervolgens het laatste element van die rij.
## Oef5
Het juiste antwoord is arr[:, -1] (antwoord 3). We kunnen alle elementen van een bepaalde dimensie opvragen met ':'. Hier is dat dus: alle rijen van de laatste kolom.
## Oef6
Je krijgt een foutmelding (antwoord 1). Je moest de waarde dus zelfs niet afdrukken, want de fout gebeurt bij de creatie van de array. Een np.int8 heeft als grootste waarde 127 en 128 is dus te groot. Let op: NumPy zal je niet altijd waarschuwen wanneer een waarde te groot is. (maar hier dus wel)
## Oef7
De waarde is -16 (antwoord 3). Hier zijn de waarden van de array niet te groot voor een np.int8. Bij de optelling worden de waarden echter wel te groot. Omdat de fout gebeurt tijdens de verwerking van de array, worden we niet gewaarschuwd en gebeurt er een *wrap-around*: 127 + 1 zou 128 worden, maar bij een np.int8 wordt dat -128 (het kleinst mogelijke getal). 127 + 2 wordt -127. 127 + 3 wordt -126...

Om te onthouden: wanneer je met integer werkt, gebruikt je best in eerst instantie np.int64 (de standaard). Pas wanneer je merkt dat je problemen krijgt met het geheugengebruik, kun je eens kijken of je geen kleinere integer kunt gebruiken.
## Oef8
De waarde is 'inf' (oneindig), maar je krijgt wel een waarschuwing omdat je deelt door 0. Het probleem is dat *np.full_like* een array maakt met hetzelfde type als *arr*. (np.int8 dus) De waarde 256 is te groot voor een np.int8 en met de *wrap-around* komen we (toevallig) uit op 0. En NumPy geeft als resultaat $\infty$ (oneindig).
## Oef9
Om ervoor te zorgen dat we het type van *arr* niet overnemen bij *np.full_like*, kunnen we een eigen type invullen. Een int16 is al voldoende:
`arr_2 = np.full_like(arr, 256, dtype=np.int16)`
## Oef10
Er waren hier verschillende mogelijkheden. Het probleem hier is dat door de append van een string het type van de array is veranderd. De drie getallen zijn teksten geworden. Het is dus niet voldoende om de som te nemen van de eerste drie elementen (np.sum(arr[:-1])). We moeten die elementen ook omzetten naar integers. Dat hebben we niet gezien, maar chatgpt kon je hier zeker bij helpen:

Je kon de functie np.int8() gebruiken: `print(np.sum(np.int8(arr[:-1])))`


Je kon ook np.astype() gebruiken: `print(np.sum((np.astype(arr[:-1], np.int8))))`
